version: '3.7'

volumes:
  home-dir:
  db-dir:

services:
  composer:
    restart: 'no'
    image: composer:latest
    network_mode: bridge
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    command: install
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - home-dir:/home/user
      - .:/app
    environment:
      - HOME=/home/user
#  node:
#    image: "node:10.15.3-jessie"
#    container_name: node
#    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
#    restart: on-failure
#    network_mode: bridge
#    working_dir: /home/node/app
#    volumes:
#      - /etc/passwd:/etc/passwd:ro
#      - /etc/group:/etc/group:ro
#      - home-dir:/home/node
#      - ./:/home/node/app
#    environment:
#      #      - NODE_ENV=production
#      - NODE_ENV=dev
#      - HOME=/home/node
#    command: bash -c "yarn install && yarn build"

  db:
    image: mariadb:10.0
    restart: on-failure
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-dir:/var/lib/mysql:rw
      - ./docker/db:/docker-entrypoint-initdb.d

  php7:
    build:
      context: ./docker/php7.3/
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    restart: on-failure
    network_mode: bridge
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/app:rw
      - home-dir:/home/user
      - './:/var/www/html/'
    environment:
      - HOME=/home/user
      - COMPOSER_MEMORY_LIMIT=-1
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    depends_on:
#      - node
      - composer
      - db
    links:
      - db

  nginx:
    image: 'nginx:1.10'
    restart: on-failure
    network_mode: bridge
    ports:
      - '80:80'
    volumes:
      - './public:/var/www/html/public/'
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7
#      - node
      - composer
    links:
      - php7


networks:
  default:
    external:
      name: bridge
